<a href="https://colab.research.google.com/github/dwvicy/zero-to-GANs/blob/master/tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Essential mathematical functions in Pytorch

### Implementing  essential Mathematical Operations in PyTorch (with examples)


What is PyTorch really?

1.   Open-source scientific computing library based in python used as a replacement for NumPy.
2.   Used extensively for research purposes.

What are Tensors?

Tensors are the basic data structures of PyTorch. They are multi-dimensional arrays with a uniform data type. They are just like numpy ndarrays and can be used on a GPU to accelerate computing.

We would discuss five interesting functions in the torch library used to implement the heavy mathematics behind our deep learning models.

- torch.floor() - to obtain a tensor with floor of elements in the input tensor. (where floor is the largest integer, less than or equal to each element)
- torch.mean() - computes the mean of all element in the input tensor
- torch.sigmoid() - computes the sigmoid of each element in the input tensor
- torch.exp() -  computes the exponential of the elements in the input tensor
- torch.reshape() - Reshapes the input tensor into the desired shape as specified in the arguments

In [0]:
# Import torch and other required modules
import torch

## Function 1 - torch.floor() 

Used to obtain a tensor with floor of elements in the input tensor. (where floor is the largest integer, less than or equal to each element)


In [0]:
# Example 1 - Using the tensor.floor() on a given input tensor
t = torch.tensor([3.4, 8.8, 7.6, 5.4])
torch.floor(t)

tensor([3., 8., 7., 5.])

After running the cell you will observe that you get a tensor with integer values as output. If you apply the torch.floor() function to any input tensor containing decimal values, it will remove the decimal part and use the integer part. 

In [0]:
# Example 2 - Using the tensor.floor() function on a randomly generated function
t1 = torch.rand(2,3) # generates a tensor of shape (2,3) with random values between 0 and 1
torch.floor(t1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In this example, we used the torch.rand() function to generate a tensor with random values between 0 and 1. When you run the cell you'll see that the value of all the elements is 0. This is because the randomly generated tensor has values between 0 and 1, hence the integer part is 0 in all cases.

In [0]:
# Example 3 -  Using tensor.floor() function on integers
t2 = torch.LongTensor([0.8, 21.8])
torch.floor(t2)

RuntimeError: ignored

Here the floor function isn't working as the tensor is a Long Tensor which has a dtype of 64-bit integer (signed). As this operation is a not implemented for Long Tensor type, it breaks. You can learn more about the nine different types of CPU and GPU tensors over [here.](https://pytorch.org/docs/stable/tensors.html)

You can use this function when you want to obtain element wise floor of a tensor. This function is widely used in deep learning models and can also be used for vectorization. 

## Function 2 - torch.mean()

Returns the mean of all elements of the input tensor


In [0]:
# Example 1 - working
t3 = torch.rand(5,5)
torch.mean(t3)

tensor(0.5586)

When we generate a random tensor with elements of values between 0 and 1, the mean of the tensor is returned when we used the torch.mean() function

In [0]:
# Example 2 - working

t4 = torch.empty(2,3)
t4.random_(0,230)


tensor([[183., 198.,  85.],
        [130.,  77., 202.]])

In [0]:
torch.mean(t4)

tensor(145.8333)

Here we initialize as empty tensor and then generate random values in the empty tensor with values between 0 to 230. We can compute the mean as shown.

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
t5 = torch.empty((3,5), dtype=int)
t5.random_(0,230)

tensor([[102, 200,   7, 162,  46],
        [ 72, 193,  12, 147, 192],
        [ 71, 168, 154, 143,  64]])

In [0]:
torch.mean(t5)

RuntimeError: ignored

This function can be used to calculate the mean of the tensor.

## Function 3 - torch.sigmoid()

Returns a tensor with sigmoid of all elements in the input matrix

In [0]:
# Example 1 - working
t3 = torch.rand(5,5)
torch.sigmoid(t3)

tensor([[0.5960, 0.5624, 0.6087, 0.6568, 0.6357],
        [0.5981, 0.7286, 0.7047, 0.7004, 0.7307],
        [0.6571, 0.5543, 0.5802, 0.7221, 0.5150],
        [0.5456, 0.5503, 0.6641, 0.6632, 0.5807],
        [0.5357, 0.7300, 0.7292, 0.5872, 0.6187]])

In [0]:
# Example 2 - working
t4 = torch.randn(5,5)
t4


tensor([[ 0.3875,  0.7180,  1.9219,  0.6843, -1.1857],
        [ 1.1380,  1.3209,  0.4670,  1.1130,  0.3986],
        [-0.4034, -0.4874, -0.1893, -0.0123,  0.9571],
        [-1.4511, -0.1595, -0.9897,  0.0215,  1.8938],
        [-0.6958, -0.0243,  0.3164,  0.1206, -0.6863]])

In [0]:
torch.sigmoid(t4)

tensor([[0.5957, 0.6722, 0.8724, 0.6647, 0.2340],
        [0.7573, 0.7893, 0.6147, 0.7527, 0.5984],
        [0.4005, 0.3805, 0.4528, 0.4969, 0.7225],
        [0.1898, 0.4602, 0.2710, 0.5054, 0.8692],
        [0.3327, 0.4939, 0.5784, 0.5301, 0.3349]])

In [0]:
# Example 3 - breaking (to illustrate when it breaks)

tt1 = torch.tensor([9, 8])
print(torch.sigmoid(tt1))

RuntimeError: ignored

sigmoid function is not implemented for the Long data type integer

## Function 4 - torch.exp()

Returns a tensor with exponential of every element in the input tensor

In [0]:
# Example 1 -  working
t = torch.rand(5,4)
torch.exp(t)

tensor([[1.0268, 1.1486, 2.2025, 2.6137],
        [1.1103, 2.4679, 2.3305, 2.5569],
        [1.3067, 1.3752, 1.8610, 1.7453],
        [1.2251, 1.7311, 1.3639, 1.9528],
        [1.0349, 2.5356, 1.9604, 2.3402]])

In [0]:
# Example 2 - working
t = torch.randn(4,5)
torch.exp(t)

tensor([[ 1.6652,  1.9396,  1.9922,  0.7699,  4.2354],
        [ 0.4029,  1.1843,  0.6758,  0.1736,  0.1198],
        [ 0.8525,  1.8410,  0.8260,  0.8440, 20.8023],
        [ 0.4721, 11.4348,  1.0345,  0.7777,  0.4395]])

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
t = torch.tensor([9,8])
torch.exp(t)

RuntimeError: ignored

the exp function doesn't work properly with the long data type

## Function 5 - torch.reshape

This function is used to reshape any given tensor.

In [0]:
# Example 1 - working
t = torch.randn((5,5))
torch.reshape(t,(1, 25))

tensor([[-0.0572, -0.1196,  0.1221,  0.9894,  0.7399, -0.0160,  0.3031,  2.2812,
         -0.4147, -0.0584,  0.2419,  0.0719, -1.1091, -0.3548,  0.2199, -1.1813,
         -0.9990,  0.0940, -0.9098, -0.5352,  0.6984,  0.4260,  0.9967, -0.9529,
         -0.3942]])

it takes two arguments, the input tensor and the shape that we want as an output

In [0]:
# Example 2 - working
t = torch.rand((2, 4))
torch.reshape(t, (1, 8))

tensor([[0.4822, 0.4796, 0.4893, 0.9301, 0.6394, 0.1383, 0.0790, 0.6524]])

Explanation about example

In [0]:
# Example 3 - breaking (to illustrate when it breaks)
t = torch.rand((2, 3))
torch.reshape(t,(2,5))

RuntimeError: ignored

The number of elements in the newly shaped tensor has to be equal to the elements in the input tensor

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* https://pytorch.org/docs/stable/torch.html

In [0]:
!pip install jovian --upgrade --quiet

In [0]:
import jovian

In [0]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
